knp_paginator:
    page_range: 2      # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page    # Le paramètre de requête utilisé pour indiquer la page actuelle
        sort_field_name: sort
        sort_direction_name: direction
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
