controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
quiz_country:
    path: /quiz/country/{country}
    controller: App\Controller\ChallengeKidsController::showByCountry
    methods: GET
